// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Ko6exFRNxF5a2YcWm6oupub3OegtBBE',
    appId: '1:523716467425:web:a6cac187e23ce329bff5a0',
    messagingSenderId: '523716467425',
    projectId: 'tahfidzmu-db5d9',
    authDomain: 'tahfidzmu-db5d9.firebaseapp.com',
    storageBucket: 'tahfidzmu-db5d9.firebasestorage.app',
    measurementId: 'G-QFG27KQ31S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1McuS1-UNPb5eYcIcQ6Er8vMLuTb5W9k',
    appId: '1:523716467425:android:6365418f06cc9729bff5a0',
    messagingSenderId: '523716467425',
    projectId: 'tahfidzmu-db5d9',
    storageBucket: 'tahfidzmu-db5d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcUSKWnFcP497CZoyrPNXGxlR8jcVCF2Q',
    appId: '1:523716467425:ios:dbbcab0f02fcc2abbff5a0',
    messagingSenderId: '523716467425',
    projectId: 'tahfidzmu-db5d9',
    storageBucket: 'tahfidzmu-db5d9.firebasestorage.app',
    iosBundleId: 'com.tahfidz.tahfidzApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcUSKWnFcP497CZoyrPNXGxlR8jcVCF2Q',
    appId: '1:523716467425:ios:dbbcab0f02fcc2abbff5a0',
    messagingSenderId: '523716467425',
    projectId: 'tahfidzmu-db5d9',
    storageBucket: 'tahfidzmu-db5d9.firebasestorage.app',
    iosBundleId: 'com.tahfidz.tahfidzApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Ko6exFRNxF5a2YcWm6oupub3OegtBBE',
    appId: '1:523716467425:web:8feeed779a7d8407bff5a0',
    messagingSenderId: '523716467425',
    projectId: 'tahfidzmu-db5d9',
    authDomain: 'tahfidzmu-db5d9.firebaseapp.com',
    storageBucket: 'tahfidzmu-db5d9.firebasestorage.app',
    measurementId: 'G-N13ZFM5QJF',
  );
}
